name: goreleaser

on:
  push:
    tags:
      - "v*"

env:
  TAG: ${{ github.ref_name }}

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: true

      - name: install mockery
        run: go install github.com/vektra/mockery/v2@v2.43.2

      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ env.TAG }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
